version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: health_blog_postgres
    environment:
      POSTGRES_DB: health_blog_admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - health_blog_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: health_blog_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@healthblog.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - health_blog_network

volumes:
  postgres_data:

networks:
  health_blog_network:
    driver: bridge
