version: '3.8'

services:
  # Supabase services
  supabase-db:
    image: supabase/postgres:15.1.0.117
    container_name: supabase-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - supabase-db-data:/var/lib/postgresql/data

  supabase-studio:
    image: supabase/studio
    container_name: supabase-studio
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://supabase-meta:8080
      POSTGRES_PASSWORD: password
      DEFAULT_ORGANIZATION: Default Organization
      DEFAULT_PROJECT: Default Project

  supabase-meta:
    image: supabase/postgres-meta:v0.68.0
    container_name: supabase-meta
    restart: unless-stopped
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PASSWORD: password

  # Neo4j service
  neo4j:
    image: neo4j:5.15.0
    container_name: neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  # ChromaDB service
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    restart: unless-stopped
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-reminder-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - SUPABASE_URL=http://supabase-db:5432
      - SUPABASE_KEY=your-secret-key
      - SUPABASE_DB_PASSWORD=password
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your-neo4j-password
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - supabase-db
      - neo4j
      - chroma

volumes:
  supabase-db-data:
  neo4j-data:
  neo4j-logs:
  chroma-data: 